name: kitehcoin
# Running 'snapcraft register <name>' is advised
version: '1.1.0'
summary: Reference client of Kitehcoin, a peer-to-peer digital currency like Bitcoin.
description: |
  Kitehcoin is a community-driven cryptocurrency that was inspired by Dogecoin. The Kitehcoin Core software allows anyone to operate a node in the Kitehcoin blockchain networks and uses the Scrypt hashing method for Proof of Work. It is adapted from Bitcoin Core and other cryptocurrencies.

grade: stable
confinement: strict
base: core22
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
  - build-on: i386
    build-for: i386

apps:
  d:
    command: bin/kitehcoind
    plugs: [home, removable-media, network, network-bind]
    environment:
      # Override HOME so the datadir is located at ~/snap/kitehcoin-core/common/.kitehcoin/ instead of ~/snap/kitehcoin-core/current/.kitehcoin/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command-chain: [bin/desktop-launch]
    command: bin/kitehcoin-qt
    plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  cli:
    command: bin/kitehcoin-cli
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON
  tx:
    command: bin/kitehcoin-tx
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON
  test:
    command: bin/test_kitehcoin
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  desktop-qt5:
    # So desktop-launch from qt5 is usable
    # Adapted from https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    source-commit: ec861254c2a1d2447b2c589446e6cdf04c75c260
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - fonts-ubuntu
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - libgtk2.0-0
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  kitehcoin:
    plugin: nil
    override-build: |
      echo "This script is viewable at https://github.com/Kitehcoin/kitehcoin/blob/master/contrib/snap/snapcraft.yaml"
      echo "Downloading files..."
      if [ "$CRAFT_ARCH_TRIPLET" = "i386-linux-gnu" ]; then # snap designates 32-bit as i386, but kitehcoin designates it as i686
        BUILD_ARCH_TRIPLET=i686-pc-linux-gnu
      else
        BUILD_ARCH_TRIPLET=$CRAFT_ARCH_TRIPLET
      fi
      wget https://github.com/Kitehcoin/kitehcoin/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/kitehcoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
      wget https://github.com/Kitehcoin/gitian.sigs/archive/refs/heads/master.tar.gz
      tar -xvf master.tar.gz
      echo "Verifying secure hash matches signed values..."
      checksum=$(sha256sum kitehcoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz)
      if ! (grep -r $checksum * | grep kitehcoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz); then
        echo "Secure hash not verified."
        return
      else
        echo "Secure hash verified."
      fi
      tar -xvf kitehcoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
      echo "Running tests..."
      if ! (kitehcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_kitehcoin); then
        echo "Kitehcoin tests failed."
        return
      else
        echo "Kitehcoin tests passed."
      fi
      wget https://raw.githubusercontent.com/Kitehcoin/kitehcoin/v${SNAPCRAFT_PROJECT_VERSION}/doc/release-notes.md
      cat release-notes.md
      echo "Installing Kitehcoin Core..."
      echo "Version ${SNAPCRAFT_PROJECT_VERSION}"
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin kitehcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/kitehcoind
      if ! ([ "$BUILD_ARCH_TRIPLET" = "aarch64-linux-gnu" ]); then # there is no official kitehcoin-qt build on arm64
        install -m 0755 -D -t $CRAFT_PART_INSTALL/bin kitehcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/kitehcoin-qt
      fi
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin kitehcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/kitehcoin-cli
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin kitehcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/kitehcoin-tx
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin kitehcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_kitehcoin
      wget https://raw.githubusercontent.com/Kitehcoin/kitehcoin/master/share/pixmaps/kitehcoin128.png
      install -m 0644 -D -t $CRAFT_PART_INSTALL/share/pixmaps kitehcoin128.png
    build-packages:
      - wget
    after:
      - desktop-qt5
